In [21]:
from pymongo import MongoClient
import pandas as pd
import time
import requests
import json
from getpass import getpass
from pandas import json_normalize
import os

In [22]:
token = os.getenv("token")

In [43]:
#Mongo conection
client = MongoClient("localhost:27017")
client

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

In [46]:
db = client["Ironhack"]
c = db.get_collection("companies")
c

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'Ironhack'), 'companies')

In [47]:
c.find_one()

{'_id': ObjectId('52cdef7c4bab8bd675297d8a'),
 'name': 'Wetpaint',
 'permalink': 'abc2',
 'crunchbase_url': 'http://www.crunchbase.com/company/wetpaint',
 'homepage_url': 'http://wetpaint-inc.com',
 'blog_url': 'http://digitalquarters.net/',
 'blog_feed_url': 'http://digitalquarters.net/feed/',
 'twitter_username': 'BachelrWetpaint',
 'category_code': 'web',
 'number_of_employees': 47,
 'founded_year': 2005,
 'founded_month': 10,
 'founded_day': 17,
 'deadpooled_year': 1,
 'tag_list': 'wiki, seattle, elowitz, media-industry, media-platform, social-distribution-system',
 'alias_list': '',
 'email_address': 'info@wetpaint.com',
 'phone_number': '206.859.6300',
 'description': 'Technology Platform Company',
 'created_at': datetime.datetime(2007, 5, 25, 6, 51, 27),
 'updated_at': 'Sun Dec 08 07:15:44 UTC 2013',
 'overview': '<p>Wetpaint is a technology platform company that uses its proprietary state-of-the-art technology and expertise in social media to build and monetize audiences for digital publishers. Wetpaint’s own online property, Wetpaint Entertainment, an entertainment news site that attracts more than 12 million unique visitors monthly and has over 2 million Facebook fans, is a proof point to the company’s success in building and engaging audiences. Media companies can license Wetpaint’s platform which includes a dynamic playbook tailored to their individual needs and comprehensive training. Founded by Internet pioneer Ben Elowitz, and with offices in New York and Seattle, Wetpaint is backed by Accel Partners, the investors behind Facebook.</p>',
 'image': {'available_sizes': [[[150, 75],
    'assets/images/resized/0000/3604/3604v14-max-150x150.jpg'],
   [[250, 125], 'assets/images/resized/0000/3604/3604v14-max-250x250.jpg'],
   [[450, 225], 'assets/images/resized/0000/3604/3604v14-max-450x450.jpg']]},
 'products': [{'name': 'Wikison Wetpaint', 'permalink': 'wetpaint-wiki'},
  {'name': 'Wetpaint Social Distribution System',
   'permalink': 'wetpaint-social-distribution-system'}],
 'relationships': [{'is_past': False,
   'title': 'Co-Founder and VP, Social and Audience Development',
   'person': {'first_name': 'Michael',
    'last_name': 'Howell',
    'permalink': 'michael-howell'}},
  {'is_past': False,
   'title': 'Co-Founder/CEO/Board of Directors',
   'person': {'first_name': 'Ben',
    'last_name': 'Elowitz',
    'permalink': 'ben-elowitz'}},
  {'is_past': False,
   'title': 'COO/Board of Directors',
   'person': {'first_name': 'Rob',
    'last_name': 'Grady',
    'permalink': 'rob-grady'}},
  {'is_past': False,
   'title': 'SVP, Strategy and Business Development',
   'person': {'first_name': 'Chris',
    'last_name': 'Kollas',
    'permalink': 'chris-kollas'}},
  {'is_past': False,
   'title': 'Board',
   'person': {'first_name': 'Theresia',
    'last_name': 'Ranzetta',
    'permalink': 'theresia-ranzetta'}},
  {'is_past': False,
   'title': 'Board Member',
   'person': {'first_name': 'Gus',
    'last_name': 'Tai',
    'permalink': 'gus-tai'}},
  {'is_past': False,
   'title': 'Board',
   'person': {'first_name': 'Len',
    'last_name': 'Jordan',
    'permalink': 'len-jordan'}},
  {'is_past': False,
   'title': 'Head of Technology and Product',
   'person': {'first_name': 'Alex',
    'last_name': 'Weinstein',
    'permalink': 'alex-weinstein'}},
  {'is_past': True,
   'title': 'CFO',
   'person': {'first_name': 'Bert',
    'last_name': 'Hogue',
    'permalink': 'bert-hogue'}},
  {'is_past': True,
   'title': 'CFO/ CRO',
   'person': {'first_name': 'Brian',
    'last_name': 'Watkins',
    'permalink': 'brian-watkins'}},
  {'is_past': True,
   'title': 'Senior Vice President, Marketing',
   'person': {'first_name': 'Rob',
    'last_name': 'Grady',
    'permalink': 'rob-grady'}},
  {'is_past': True,
   'title': 'VP, Technology and Product',
   'person': {'first_name': 'Werner',
    'last_name': 'Koepf',
    'permalink': 'werner-koepf'}},
  {'is_past': True,
   'title': 'VP Marketing',
   'person': {'first_name': 'Kevin',
    'last_name': 'Flaherty',
    'permalink': 'kevin-flaherty'}},
  {'is_past': True,
   'title': 'VP User Experience',
   'person': {'first_name': 'Alex',
    'last_name': 'Berg',
    'permalink': 'alex-berg'}},
  {'is_past': True,
   'title': 'VP Engineering',
   'person': {'first_name': 'Steve',
    'last_name': 'McQuade',
    'permalink': 'steve-mcquade'}},
  {'is_past': True,
   'title': 'Executive Editor',
   'person': {'first_name': 'Susan',
    'last_name': 'Mulcahy',
    'permalink': 'susan-mulcahy'}},
  {'is_past': True,
   'title': 'VP Business Development',
   'person': {'first_name': 'Chris',
    'last_name': 'Kollas',
    'permalink': 'chris-kollas'}}],
 'competitions': [{'competitor': {'name': 'Wikia', 'permalink': 'wikia'}},
  {'competitor': {'name': 'JotSpot', 'permalink': 'jotspot'}},
  {'competitor': {'name': 'Socialtext', 'permalink': 'socialtext'}},
  {'competitor': {'name': 'Ning by Glam Media', 'permalink': 'ning'}},
  {'competitor': {'name': 'Soceeo', 'permalink': 'soceeo'}},
  {'competitor': {'name': 'Yola', 'permalink': 'yola'}},
  {'competitor': {'name': 'SocialGO', 'permalink': 'socialgo'}},
  {'competitor': {'name': 'IslamNor', 'permalink': 'islamnor'}}],
 'providerships': [],
 'total_money_raised': '$39.8M',
 'funding_rounds': [{'id': 888,
   'round_code': 'a',
   'source_url': 'http://seattlepi.nwsource.com/business/246734_wiki02.html',
   'source_description': '',
   'raised_amount': 5250000,
   'raised_currency_code': 'USD',
   'funded_year': 2005,
   'funded_month': 10,
   'funded_day': 1,
   'investments': [{'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None}]},
  {'id': 889,
   'round_code': 'b',
   'source_url': 'http://pulse2.com/2007/01/09/wiki-builder-website-wetpaint-welcomes-95m-funding/',
   'source_description': '',
   'raised_amount': 9500000,
   'raised_currency_code': 'USD',
   'funded_year': 2007,
   'funded_month': 1,
   'funded_day': 1,
   'investments': [{'company': None,
     'financial_org': {'name': 'Accel Partners',
      'permalink': 'accel-partners'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None}]},
  {'id': 2312,
   'round_code': 'c',
   'source_url': 'http://www.accel.com/news/news_one_up.php?news_id=185',
   'source_description': 'Accel',
   'raised_amount': 25000000,
   'raised_currency_code': 'USD',
   'funded_year': 2008,
   'funded_month': 5,
   'funded_day': 19,
   'investments': [{'company': None,
     'financial_org': {'name': 'DAG Ventures', 'permalink': 'dag-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Accel Partners',
      'permalink': 'accel-partners'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Trinity Ventures',
      'permalink': 'trinity-ventures'},
     'person': None},
    {'company': None,
     'financial_org': {'name': 'Frazier Technology Ventures',
      'permalink': 'frazier-technology-ventures'},
     'person': None}]}],
 'investments': [],
 'acquisition': {'price_amount': 30000000,
  'price_currency_code': 'USD',
  'term_code': 'cash_and_stock',
  'source_url': 'http://allthingsd.com/20131216/viggle-tries-to-bulk-up-its-social-tv-business-by-buying-wetpaint/?mod=atdtweet',
  'source_description': ' Viggle Tries to Bulk Up Its Social TV Business by Buying Wetpaint',
  'acquired_year': 2013,
  'acquired_month': 12,
  'acquired_day': 16,
  'acquiring_company': {'name': 'Viggle', 'permalink': 'viggle'}},
 'acquisitions': [],
 'offices': [{'description': '',
   'address1': '710 - 2nd Avenue',
   'address2': 'Suite 1100',
   'zip_code': '98104',
   'city': 'Seattle',
   'state_code': 'WA',
   'country_code': 'USA',
   'latitude': 47.603122,
   'longitude': -122.333253},
  {'description': '',
   'address1': '270 Lafayette Street',
   'address2': 'Suite 505',
   'zip_code': '10012',
   'city': 'New York',
   'state_code': 'NY',
   'country_code': 'USA',
   'latitude': 40.7237306,
   'longitude': -73.9964312}],
 'milestones': [{'id': 5869,
   'description': "Wetpaint named in Lead411's Hottest Seattle Companies list",
   'stoned_year': 2010,
   'stoned_month': 6,
   'stoned_day': 8,
   'source_url': 'http://www.lead411.com/seattle-companies.html',
   'source_text': None,
   'source_description': 'LEAD411 LAUNCHES "HOTTEST SEATTLE COMPANIES" AWARDS',
   'stoneable_type': 'Company',
   'stoned_value': None,
   'stoned_value_type': None,
   'stoned_acquirer': None,
   'stoneable': {'name': 'Wetpaint', 'permalink': 'wetpaint'}},
  {'id': 8702,
   'description': 'Site-Builder Wetpaint Makes One For Itself, Using the Demand Media Playbook',
   'stoned_year': 2010,
   'stoned_month': 9,
   'stoned_day': 6,
   'source_url': 'http://mediamemo.allthingsd.com/20100906/site-builder-wetpaint-makes-one-for-itself-using-the-demand-media-playbook/',
   'source_text': None,
   'source_description': 'All Things D',
   'stoneable_type': 'Company',
   'stoned_value': None,
   'stoned_value_type': None,
   'stoned_acquirer': None,
   'stoneable': {'name': 'Wetpaint', 'permalink': 'wetpaint'}}],
 'video_embeds': [],
 'screenshots': [{'available_sizes': [[[150, 86],
     'assets/images/resized/0016/0929/160929v2-max-150x150.png'],
    [[250, 143], 'assets/images/resized/0016/0929/160929v2-max-250x250.png'],
    [[450, 258], 'assets/images/resized/0016/0929/160929v2-max-450x450.png']],
   'attribution': None}],
 'external_links': [{'external_url': 'http://www.geekwire.com/2011/rewind-ben-elowitz-wetpaint-ceo-building-type-media-company',
   'title': 'GeekWire interview: Rewind - Ben Elowitz, Wetpaint CEO, on building a new type of media company'},
  {'external_url': 'http://techcrunch.com/2012/06/17/search-and-social-how-two-will-soon-become-one/',
   'title': 'Guest post by CEO Ben Elowitz in TechCrunch'},
  {'external_url': 'http://allthingsd.com/20120516/what-to-expect-when-facebook-is-expecting-five-predictions-for-facebooks-first-public-year/',
   'title': 'Guest post by CEO Ben Elowitz in AllThingsD'},
  {'external_url': 'http://adage.com/article/digitalnext/facebook-biggest-player-advertising-s-540-billion-world/235708/',
   'title': 'Guest post by CEO Ben Elowitz in AdAge'},
  {'external_url': 'http://www.businessinsider.com/facebook-captures-14-percent-of-our-online-attention-but-only-4-percent-of-ad-spending-online-2012-6',
   'title': 'Guest post by CEO Ben Elowitz in Business Insider'},
  {'external_url': 'http://allfacebook.com/wetpaint-media-data_b75963',
   'title': 'AllFacebook coverage of Wetpaint'},
  {'external_url': 'http://adage.com/article/digital/celeb-site-wetpaint-shows-media-profit-facebook/237828/',
   'title': 'Profile of Wetpaint in Ad Age'},
  {'external_url': 'http://allthingsd.com/20121018/how-to-boost-your-facebook-traffic-tips-and-tricks-from-wetpaint/',
   'title': 'Interview with Wetpaint CEO Ben Elowitz in All Things D'},
  {'external_url': 'http://www.xconomy.com/seattle/2012/10/19/wetpaint-starts-licensing-its-facebook-based-media-distribution-tech/',
   'title': 'Profile of Wetpaint in Xconomy'}],
 'partners': []}

In [26]:
filter= {"number_of_employees":{"$gte":90, "$lte":140},"category_code":"games_video"}
projection = {"_id":0, "name":1,"number_of_employees":1, "offices.country_code": 1,"offices.city":1,"category_code":1,"outcode":1}

results1 = list(c.find(filter, projection).sort("number_of_employees", 1))

In [27]:
totalcount = c.count_documents(filter)
print(totalcount)

19

In [28]:
## USA is the country with most start-ups that meet the above requirements. 
filter1= {"number_of_employees":{"$gte":90, "$lte":140},"category_code":"games_video","offices.country_code":"USA"}
usa_count =c.count_documents(filter1)
usa_count

13

In [29]:

filter2= {"number_of_employees":{"$gte":90, "$lte":140},"category_code":"games_video","offices.country_code":"USA"}
projection = {"_id":0, "name":1,"number_of_employees":1, "offices.state_code":1,"category_code":1,"outcode":1}

results2 = list(c.find(filter2, projection).sort("number_of_employees", 1))
pd.DataFrame(results2)

,name,category_code,number_of_employees,offices
0,hi5,games_video,100,[{'state_code': 'CA'}]
1,Social Gaming Network,games_video,100,"[{'state_code': 'CA'}, {'state_code': 'CA'}]"
2,VBS TV,games_video,100,[{'state_code': 'NY'}]
3,ZillionTV,games_video,100,"[{'state_code': 'CA'}, {'state_code': 'CA'}]"
4,Exent,games_video,100,"[{'state_code': 'NY'}, {'state_code': None}, {..."
5,iWin,games_video,103,[{'state_code': 'CA'}]
6,RockYou,games_video,106,[{'state_code': 'CA'}]
7,G5 Entertainment,games_video,107,"[{'state_code': None}, {'state_code': None}, {..."
8,Zynga,games_video,115,"[{'state_code': 'CA'}, {'state_code': None}, {..."
9,Livestream,games_video,120,[{'state_code': 'NY'}]
10,Modern Feed,games_video,123,[{'state_code': 'CA'}]
11,RGB Networks,games_video,125,[{'state_code': 'CA'}]
12,Z2Live,games_video,130,[{'state_code': 'WA'}]

In [30]:
#ca = 12
filter2= {"number_of_employees":{"$gte":90, "$lte":140},"category_code":"games_video","offices.state_code":"CA"}
projection = {"_id":0, "name":1,"number_of_employees":1, "offices.city":1,"category_code":1,"outcode":1}

# CA = list(c.find(filter2, projection).sort("number_of_employees", 1))
# pd.DataFrame(CA)

#ny = 4

In [31]:
filter3= {"number_of_employees":{"$gte":90, "$lte":140},"category_code":"games_video","offices.state_code":"NY"}
projection = {"_id":0, "name":1,"number_of_employees":1, "offices.city":1,"category_code":1,"outcode":1}

NY = list(c.find(filter3, projection).sort("number_of_employees", 1))
pd.DataFrame(NY)

,name,category_code,number_of_employees,offices
0,VBS TV,games_video,100,[{'city': 'Brooklyn'}]
1,Exent,games_video,100,"[{'city': 'New York'}, {'city': 'Petach-Tikva'..."
2,Livestream,games_video,120,[{'city': 'New York'}]

In [32]:
filter3= {"number_of_employees":{"$gte":90, "$lte":140},"category_code":"games_video","offices.state_code":"WA"}
projection = {"_id":0, "name":1,"number_of_employees":1, "offices.city":1,"category_code":1,"outcode":1}

WA = list(c.find(filter3, projection).sort("number_of_employees", 1))
pd.DataFrame(WA)

     name category_code  number_of_employees                offices
0  Z2Live   games_video                  130  [{'city': 'Seattle'}]

In [33]:
filtering= {"number_of_employees":{"$gte":90, "$lte":140},"category_code":"games_video"}
projection= {"_id":0, "name":1,"number_of_employees":1, "offices.city":1,"category_code":1,"offices.latitude":1,"offices.longitude":1,"offices.country_code":1,"outcode":1}
choose_companies = list(c.find(filtering, projection).sort("number_of_employees", 1))
choose_companies

[{'name': 'hi5',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': 37.788668,
    'longitude': -122.400558}]},
 {'name': 'mig33',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'Singapore',
    'country_code': 'SGP',
    'latitude': 37.580304,
    'longitude': -122.343679}]},
 {'name': 'Social Gaming Network',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'Los Angeles',
    'country_code': 'USA',
    'latitude': 37.446823,
    'longitude': -122.161523},
   {'city': 'Beverly Hills',
    'country_code': 'USA',
    'latitude': 34.0698494,
    'longitude': -118.4054182}]},
 {'name': 'VBS TV',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'Brooklyn',
    'country_code': 'USA',
    'latitude': 40.720764,
    'longitude': -73.957968}]},
 {'name': 'Whereismyboss',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': '',
    'country_code': 'IND',
    'latitude': None,
    'longitude': None}]},
 {'name': 'ZillionTV',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'Sunnyvale',
    'country_code': 'USA',
    'latitude': 37.3738725,
    'longitude': -121.9973546},
   {'city': 'Santa Monica',
    'country_code': 'USA',
    'latitude': 34.016838,
    'longitude': -118.500603}]},
 {'name': 'Exent',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'New York',
    'country_code': 'USA',
    'latitude': 40.7523796,
    'longitude': -74.005568},
   {'city': 'Petach-Tikva',
    'country_code': 'ISR',
    'latitude': None,
    'longitude': None},
   {'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': 37.787646,
    'longitude': -122.402759}]},
 {'name': 'iWin',
  'category_code': 'games_video',
  'number_of_employees': 103,
  'offices': [{'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': 37.781689,
    'longitude': -122.391061}]},
 {'name': '2 Minutes',
  'category_code': 'games_video',
  'number_of_employees': 105,
  'offices': [{'city': 'Paris',
    'country_code': 'FRA',
    'latitude': 48.8502056,
    'longitude': 2.3698033}]},
 {'name': 'RockYou',
  'category_code': 'games_video',
  'number_of_employees': 106,
  'offices': [{'city': 'Redwood City',
    'country_code': 'USA',
    'latitude': 37.484619,
    'longitude': -122.206893}]},
 {'name': 'G5 Entertainment',
  'category_code': 'games_video',
  'number_of_employees': 107,
  'offices': [{'city': 'Kharkov',
    'country_code': 'UKR',
    'latitude': None,
    'longitude': None},
   {'city': 'Stockholm',
    'country_code': 'SWE',
    'latitude': None,
    'longitude': None},
   {'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': None,
    'longitude': None}]},
 {'name': 'Zynga',
  'category_code': 'games_video',
  'number_of_employees': 115,
  'offices': [{'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': 37.765158,
    'longitude': -122.404234},
   {'city': '', 'country_code': 'IND', 'latitude': None, 'longitude': None},
   {'city': 'Baltimore',
    'country_code': 'USA',
    'latitude': None,
    'longitude': None},
   {'city': 'Los Angeles',
    'country_code': 'USA',
    'latitude': None,
    'longitude': None}]},
 {'name': 'Aspiro',
  'category_code': 'games_video',
  'number_of_employees': 115,
  'offices': [{'city': 'Malmo',
    'country_code': 'SWE',
    'latitude': None,
    'longitude': None}]},
 {'name': 'Livestream',
  'category_code': 'games_video',
  'number_of_employees': 120,
  'offices': [{'city': 'New York',
    'country_code': 'USA',
    'latitude': 40.726155,
    'longitude': -73.995625}]},
 {'name': 'PlayNetwork',
  'category_code': 'games_video',
  'number_of_employees': 122,
  'offices': []},
 {'name': 'Modern Feed',
  'category_code': 'games_video',
  'number_of_employees': 123,
  'offices': [{'city': 'Los Angeles',
    'country_code': 'USA',
    'latitude': 34.085749,
    'longitude': -118.343791}]},
 {'name': 'RGB Networks',
  'category_code': 'games_video',
  'number_of_employees': 125,
  'offices': [{'city': 'Sunnyvale',
    'country_code': 'USA',
    'latitude': 37.4123706,
    'longitude': -122.0216271}]},
 {'name': 'Z2Live',
  'category_code': 'games_video',
  'number_of_employees': 130,
  'offices': [{'city': 'Seattle',
    'country_code': 'USA',
    'latitude': 47.6103008,
    'longitude': -122.3399782}]},
 {'name': 'Miniclip',
  'category_code': 'games_video',
  'number_of_employees': 140,
  'offices': [{'city': '',
    'country_code': 'CHE',
    'latitude': None,
    'longitude': None}]}]

In [34]:
filtering= {"number_of_employees":{"$gte":90, "$lte":140},"category_code":"games_video","offices.country_code":"USA"}
projection= {"_id":0, "name":1,"number_of_employees":1, "offices.city":1,"category_code":1,"offices.latitude":1,"offices.longitude":1,"offices.country_code":1,"outcode":1}
usa_companies = list(c.find(filtering, projection).sort("number_of_employees", 1))
usa_companies

[{'name': 'hi5',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': 37.788668,
    'longitude': -122.400558}]},
 {'name': 'Social Gaming Network',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'Los Angeles',
    'country_code': 'USA',
    'latitude': 37.446823,
    'longitude': -122.161523},
   {'city': 'Beverly Hills',
    'country_code': 'USA',
    'latitude': 34.0698494,
    'longitude': -118.4054182}]},
 {'name': 'VBS TV',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'Brooklyn',
    'country_code': 'USA',
    'latitude': 40.720764,
    'longitude': -73.957968}]},
 {'name': 'ZillionTV',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'Sunnyvale',
    'country_code': 'USA',
    'latitude': 37.3738725,
    'longitude': -121.9973546},
   {'city': 'Santa Monica',
    'country_code': 'USA',
    'latitude': 34.016838,
    'longitude': -118.500603}]},
 {'name': 'Exent',
  'category_code': 'games_video',
  'number_of_employees': 100,
  'offices': [{'city': 'New York',
    'country_code': 'USA',
    'latitude': 40.7523796,
    'longitude': -74.005568},
   {'city': 'Petach-Tikva',
    'country_code': 'ISR',
    'latitude': None,
    'longitude': None},
   {'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': 37.787646,
    'longitude': -122.402759}]},
 {'name': 'iWin',
  'category_code': 'games_video',
  'number_of_employees': 103,
  'offices': [{'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': 37.781689,
    'longitude': -122.391061}]},
 {'name': 'RockYou',
  'category_code': 'games_video',
  'number_of_employees': 106,
  'offices': [{'city': 'Redwood City',
    'country_code': 'USA',
    'latitude': 37.484619,
    'longitude': -122.206893}]},
 {'name': 'G5 Entertainment',
  'category_code': 'games_video',
  'number_of_employees': 107,
  'offices': [{'city': 'Kharkov',
    'country_code': 'UKR',
    'latitude': None,
    'longitude': None},
   {'city': 'Stockholm',
    'country_code': 'SWE',
    'latitude': None,
    'longitude': None},
   {'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': None,
    'longitude': None}]},
 {'name': 'Zynga',
  'category_code': 'games_video',
  'number_of_employees': 115,
  'offices': [{'city': 'San Francisco',
    'country_code': 'USA',
    'latitude': 37.765158,
    'longitude': -122.404234},
   {'city': '', 'country_code': 'IND', 'latitude': None, 'longitude': None},
   {'city': 'Baltimore',
    'country_code': 'USA',
    'latitude': None,
    'longitude': None},
   {'city': 'Los Angeles',
    'country_code': 'USA',
    'latitude': None,
    'longitude': None}]},
 {'name': 'Livestream',
  'category_code': 'games_video',
  'number_of_employees': 120,
  'offices': [{'city': 'New York',
    'country_code': 'USA',
    'latitude': 40.726155,
    'longitude': -73.995625}]},
 {'name': 'Modern Feed',
  'category_code': 'games_video',
  'number_of_employees': 123,
  'offices': [{'city': 'Los Angeles',
    'country_code': 'USA',
    'latitude': 34.085749,
    'longitude': -118.343791}]},
 {'name': 'RGB Networks',
  'category_code': 'games_video',
  'number_of_employees': 125,
  'offices': [{'city': 'Sunnyvale',
    'country_code': 'USA',
    'latitude': 37.4123706,
    'longitude': -122.0216271}]},
 {'name': 'Z2Live',
  'category_code': 'games_video',
  'number_of_employees': 130,
  'offices': [{'city': 'Seattle',
    'country_code': 'USA',
    'latitude': 47.6103008,
    'longitude': -122.3399782}]}]

In [35]:
def companies_ubi(name, city, latitude, longitude):
    filtering= {"number_of_employees":{"$gte":90,"$lte":140},"category_code":"games_video"}
    projection= {"_id":0,"name":1,"number_of_employees":1,"offices.city":1,"category_code":1,"offices.latitude":1,"offices.longitude":1,"outcode":1}
    usa_companies = list(c.find(filtering, projection).sort("number_of_employees", 1))
    name = []
    latitude = []
    longitude = []
    city = []
    country = []
    for i in usa_companies:
        offices = i["offices"]

        for j in offices:
            # Check if the latitude and longitude for the current office are not None
            if j["city"] is not None and j["latitude"] is not None and j["longitude"] is not None:
                name.append(i["name"]) 
                city.append(j["city"])
                country.append(j["country_code"])
                latitude.append(j["latitude"])
                longitude.append(j["longitude"])

    return name,city,latitude,longitude

In [36]:
# filtering= {"number_of_employees":{"$gte":90,"$lte":140},"category_code":"games_video"}
# projection= {"_id":0,"name":1,"number_of_employees":1,"offices.city":1,"category_code":1,"offices.latitude":1,"offices.longitude":1,"outcode":1}
# usa_companies = list(c.find(filtering, projection).sort("number_of_employees", 1))

# name = []
# latitude = []
# longitude = []
# city = []

# for i in usa_companies:
#     offices = i["offices"]
#     for j in offices:
#         if j["city"] is not None and j["latitude"] is not None and j["longitude"] is not None:
#             name.append(i["name"]) 
#             city.append(j["city"])
#             latitude.append(j["latitude"])
#             longitude.append(j["longitude"])

In [37]:
def create_dataframe(df):
    final_list = {"Name": name,"Country":country,"City":city,"Latitude": latitude,"Longitude": longitude}
    df = pd.DataFrame(usa_companies)
    return df

In [39]:
def export_to_json(usa_companies, output_directory, output_file):
    try:
        full_file_path = os.path.join(output_directory, output_file)
        os.makedirs(output_directory, exist_ok=True)
        with open(full_file_path, 'w') as json_file:
            json.dump(usa_companies, json_file, indent=4)
        print(f"Data exported to '{full_file_path}'")
        return True
    except Exception as e:
        print(f"Error: {e}")
        return False

output_directory = 'data/'
output_file_name = 'usa_companiess.json'

result = export_to_json(usa_companies, output_directory, output_file_name)

Data exported to 'data/usa_companiess.json'

In [40]:
client = MongoClient("mongodb://localhost:27017")

db = client["Ironhack"]

data_file = 'data/usa_companiess.json'

collection_name = "usa_companiess"

with open(data_file, 'r') as json_file:
    data = json.load(json_file)

collection = db[collection_name]
collection.insert_many(data)

client.close()